import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    categoryId: "89787d42-11e3-4744-a308-934431705bd5",
    categoryName: "Exotic Indoor Plants",
    productName: "Rose",
    productImg: "someurl",
    isOutOfStock: false,
    isOnSale: true,
    productRating: 4,
    originalPrice: "50",
    salePrice: "49",
    discountedPctage: "2",
  },
  {
    _id: uuid(),
    categoryId: "d3fc7d01-923c-48ef-a6fe-415cedbe70da",
    categoryName: "Garden Plants",
    productName: "Hydrangea",
    productImg: "someurl",
    isOutOfStock: false,
    isOnSale: true,
    productRating: 3,
    originalPrice: "60",
    salePrice: "55",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryId: "152d0358-9f82-4fbd-849e-67c457f3e00d",
    categoryName: "Table Shrubs",
    productName: "Succulent",
    productImg: "someurl",
    isOutOfStock: false,
    isOnSale: true,
    productRating: 2,
    originalPrice: "80",
    salePrice: "75",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryId: "152d0358-9f82-4fbd-849e-67c457f3e00d",
    categoryName: "Table Shrubs",
    productName: "Herb",
    productImg: "someurl",
    isOutOfStock: false,
    isOnSale: true,
    productRating: 1,
    originalPrice: "94",
    salePrice: "90",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryId: "152d0358-9f82-4fbd-849e-67c457f3e00d",
    categoryName: "Table Shrubs",
    productName: "Fragrant Plants",
    productImg: "someurl",
    isOutOfStock: false,
    isOnSale: true,
    productRating: 4,
    originalPrice: "80",
    salePrice: "75",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryId: "ce934218-115a-4faf-b396-14484e2c3fcd",
    categoryName: "Seasonal Flowers",
    productName: "Climbing Vine",
    productImg: "someurl",
    isOutOfStock: false,
    isOnSale: true,
    productRating: 3,
    originalPrice: "80",
    salePrice: "75",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryId: "152d0358-9f82-4fbd-849e-67c457f3e00d",
    categoryName: "Table Shrubs",
    productName: "Ornamental Tree",
    productImg: "someurl",
    isOutOfStock: false,
    isOnSale: true,
    productRating: 2,
    originalPrice: "80",
    salePrice: "75",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryId: "ce934218-115a-4faf-b396-14484e2c3fcd",
    categoryName: "Seasonal Flowers",
    productName: "Climbing Vine",
    productImg: "someurl",
    isOutOfStock: false,
    isOnSale: true,
    productRating: 1,
    originalPrice: "80",
    salePrice: "75",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryId: "152d0358-9f82-4fbd-849e-67c457f3e00d",
    categoryName: "Table Shrubs",
    productName: "Flowering Shrub",
    productImg: "someurl",
    isOutOfStock: false,
    isOnSale: true,
    productRating: 4,
    originalPrice: "80",
    salePrice: "75",
    discountedPctage: "50",
  },
];
