import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    categoryName: "non-fiction",
    productName: "Rose",
    productImg: "someurl",
    isInStock: true,
    isOnSale: true,
    originalPrice: "50",
    discountedPrice: "49",
    discountedPctage: "2",
  },
  {
    _id: uuid(),
    categoryName: "horror",
    productName: "Hydrangea",
    productImg: "someurl",
    isInStock: true,
    isOnSale: true,
    originalPrice: "60",
    discountedPrice: "55",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryName: "fiction",
    productName: "Succulent",
    productImg: "someurl",
    isInStock: true,
    isOnSale: true,
    originalPrice: "80",
    discountedPrice: "75",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryName: "fiction",
    productName: "Herb",
    productImg: "someurl",
    isInStock: true,
    isOnSale: true,
    originalPrice: "94",
    discountedPrice: "90",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryName: "fiction",
    productName: "Fragrant Plants",
    productImg: "someurl",
    isInStock: true,
    isOnSale: true,
    originalPrice: "80",
    discountedPrice: "75",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryName: "fiction",
    productName: "Climbing Vine",
    productImg: "someurl",
    isInStock: true,
    isOnSale: true,
    originalPrice: "80",
    discountedPrice: "75",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryName: "fiction",
    productName: "Ornamental Tree",
    productImg: "someurl",
    isInStock: true,
    isOnSale: true,
    originalPrice: "80",
    discountedPrice: "75",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryName: "fiction",
    productName: "Climbing Vine",
    productImg: "someurl",
    isInStock: true,
    isOnSale: true,
    originalPrice: "80",
    discountedPrice: "75",
    discountedPctage: "50",
  },
  {
    _id: uuid(),
    categoryName: "fiction",
    productName: "Flowering Shrub",
    productImg: "someurl",
    isInStock: true,
    isOnSale: true,
    originalPrice: "80",
    discountedPrice: "75",
    discountedPctage: "50",
  },
];
